### ISSUE TITLE
JDBC creates workunits without Job Name

### ISSUE THREAD

**Issue by RussWhitehead** [hpcc-systems/hpcc-jdbc#126]
Whilst a job name is meaningless to a JDBC developer, an Admin viewing activity via ECLWatch would probably like to see something in that column of the Browse Workunits screen. I notice in Dataland there are a lot of jobs without names, so it isn't critical, but perhaps something to denote it was JDBC generated?

**Comment by rpastrana** [comment]
https://track.hpccsystems.com/browse/JDBC-20
