### ISSUE TITLE
Attempt to access metadata from Access/EasySoft results in error

### ISSUE THREAD

**Issue by RussWhitehead** [hpcc-systems/hpcc-jdbc#127]
When using the EasySoft ODBC-JDBC bridge and Microsoft Access, attempting to link tables results in
 "HPCCDBMetaData: getVersionColumns Not supported yet" .  
Not sure if implementing that interface will be enough for Access to work, but we should discuss if it is worthwhile

**Comment by rpastrana** [comment]
https://track.hpccsystems.com/browse/JDBC-17
