### ISSUE TITLE
Trace file created even though TraceToFile is not specified

### ISSUE THREAD

**Issue by RussWhitehead** [hpcc-systems/hpcc-jdbc#128]
Using ODBCTest and the EasySoft ODBC to JDBC bridge, without specifying TraceToFile=true , trace file HPCCJDBC.log is still getting written. Additionally, there is a HPCCJDBC.log.lck file created that doesn't get deleted

In this scenario files are created in C:\Program Files (x86)\Microsoft Data Access SDK 2.8\Tools\x86

**Comment by rpastrana** [comment]
https://track.hpccsystems.com/browse/JDBC-19
