### ISSUE TITLE
Consider implementing 'getMoreResults'

### ISSUE THREAD

**Issue by RussWhitehead** [hpcc-systems/hpcc-jdbc#130]
After a query using ODBCTest and EasySoft, , request to display the results always are followed with an error

SQLMoreResults returned: SQL_ERROR=-1
				:		szSqlState = "01000", *pfNativeError = 0, *pcbErrorMsg = 91
										szErrorMsg = "[Easysoft][ODBC-JDBC Gateway][HPCC Systems]HPCCStatement: getMoreResults Not supported yet."

Should we consider implementing it ?

**Comment by rpastrana** [comment]
This should be implemented as of beta-0.3.0
